### ISSUE TITLE
Changing morph rate doesn't flush the cache

### ISSUE THREAD

**Issue by Patchethium** [Hiroshiba/voicevox_engine#189]
## Description

I was considering to implement the morph feature on GUI side and played around a bit with the morph API then met this problem. For a request body, that is, accent phrase in GUI side, only its first morphing will be taken into account while changing the morph rate after that won't return a new audio file.

### Screenshot (audio included)

https://user-images.githubusercontent.com/74458240/142192551-5da40d7a-c050-41c6-89b1-716e7f1b919e.mp4

### Reproducing

Test the morph api, change the `morph_rate` argument and test it again

### Expected behavior

Changing the morph rate returns a freshly generated audio,

## Version of VOICEVOX engine

0.8.5 製品版

## OSの種類/ディストリ/バージョン

Windows

**Comment by Hiroshiba** [comment]
報告ありがとうございます！

ソースコードを見てみましたが、`morph_rate`が変わると新しい音声を合成すると思います。たぶん。

もしかしたら使われているGUIソフトウェアがキャッシュしている可能性があるかもしれません。
[`curl`を用いる方法](https://github.com/Hiroshiba/voicevox_engine/tree/921ea1d7953ac4631b0cb6d36f9f743accc6d3cc#2-%E4%BA%BA%E3%81%AE%E8%A9%B1%E8%80%85%E3%81%A7%E3%83%A2%E3%83%BC%E3%83%95%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%99%E3%82%8B%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%89)だとどうなりますか？

---

Thanks for the report!

I re-read the source code, and I think it synthesizes a new audio when `morph_rate` changes. Maybe.

Perhaps it is possible that your GUI software is caching it.
What happens if you use [`curl`](https://github.com/Hiroshiba/voicevox_engine/tree/921ea1d7953ac4631b0cb6d36f9f743accc6d3cc#2-%E4%BA%BA%E3%81%AE%E8%A9%B1%E8%80%85%E3%81%A7%E3%83%A2%E3%83%BC%E3%83%95%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%99%E3%82%8B%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%89)?

**Comment by Patchethium** [comment]
Thanks for answering, it turns out that you're right. `Postman` is handy dealing with text but becomes weird when it came to audio and images...
